In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [5]:
df_may18_week1 = pd.read_csv('data/turnstile_180505.csv')
df_may18_week2 = pd.read_csv('data/turnstile_180512.csv')
df_may18_week3 = pd.read_csv('data/turnstile_180519.csv')
df_may18_week4 = pd.read_csv('data/turnstile_180526.csv')

df_may18 = df_may18_week1.append(df_may18_week2)
df_may18 = df_may18_week1.append(df_may18_week3)
df_may18 = df_may18_week1.append(df_may18_week4)

In [6]:
df_may18

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,00:00:00,REGULAR,6598847,2235829
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,04:00:00,REGULAR,6598864,2235830
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,08:00:00,REGULAR,6598880,2235863
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,12:00:00,REGULAR,6598961,2235955
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,6599175,2236015
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,20:00:00,REGULAR,6599456,2236074
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,00:00:00,REGULAR,6599584,2236102
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,04:00:00,REGULAR,6599593,2236106
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,08:00:00,REGULAR,6599603,2236123
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,12:00:00,REGULAR,6599689,2236180
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,16:00:00,REGULAR,6599850,2236232
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,20:00:00,REGULAR,6600050,2236280
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2018,00:00:00,REGULAR,6600159,2236301
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2018,04:00:00,REGULAR,6600165,2236306
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2018,08:00:00,REGULAR,6600199,2236430
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2018,12:00:00,REGULAR,6600435,2236678
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2018,16:00:00,REGULAR,6600769,2236736
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2018,20:00:00,REGULAR,6601584,2236830
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2018,00:00:00,REGULAR,6601762,2236852
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2018,04:00:00,REGULAR,6601772,2236857
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2018,08:00:00,REGULAR,6601823,2236982
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2018,12:00:00,REGULAR,6601997,2237242
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2018,16:00:00,REGULAR,6602286,2237312
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2018,20:00:00,REGULAR,6603075,2237383
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2018,00:00:00,REGULAR,6603274,2237420
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2018,04:00:00,REGULAR,6603283,2237423
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2018,08:00:00,REGULAR,6603321,2237558
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2018,12:00:00,REGULAR,6603482,2237821
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2018,16:00:00,REGULAR,6603787,2237877
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2018,20:00:00,REGULAR,6604584,2237940
...,...,...,...,...,...,...,...,...,...,...,...
198144,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/21/2018,01:00:00,REGULAR,2891201,386598
198145,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/21/2018,05:00:00,REGULAR,2891203,386599
198146,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/21/2018,09:00:00,REGULAR,2891513,386603
198147,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/21/2018,13:00:00,REGULAR,2891937,386604
198148,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/21/2018,17:00:00,REGULAR,2892346,386609
198149,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/21/2018,21:00:00,REGULAR,2892736,386612
198150,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/22/2018,01:00:00,REGULAR,2892836,386618
198151,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/22/2018,05:00:00,REGULAR,2892839,386619
198152,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/22/2018,09:00:00,REGULAR,2893171,386621
198153,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/22/2018,13:00:00,REGULAR,2893566,386622
198154,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/22/2018,17:00:00,REGULAR,2893820,386624
198155,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/22/2018,21:00:00,REGULAR,2894008,386630
198156,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/23/2018,01:00:00,REGULAR,2894063,386634
198157,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/23/2018,05:00:00,REGULAR,2894064,386634
198158,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/23/2018,09:00:00,REGULAR,2894337,386637
198159,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/23/2018,13:00:00,REGULAR,2894747,386641
198160,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/23/2018,17:00:00,REGULAR,2895189,386649
198161,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/23/2018,21:00:00,REGULAR,2895512,386653
198162,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/24/2018,01:00:00,REGULAR,2895617,386658
198163,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/24/2018,05:00:00,REGULAR,2895622,386658
198164,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/24/2018,09:00:00,REGULAR,2895931,386664
198165,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/24/2018,13:00:00,REGULAR,2896415,386669
198166,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/24/2018,17:00:00,REGULAR,2896845,386678
198167,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/24/2018,21:00:00,REGULAR,2897231,386679
198168,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/25/2018,01:00:00,REGULAR,2897333,386683
198169,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/25/2018,05:00:00,REGULAR,2897335,386685
198170,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/25/2018,09:00:00,REGULAR,2897608,386691
198171,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/25/2018,13:00:00,REGULAR,2898001,386697
198172,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/25/2018,17:00:00,REGULAR,2898420,386700
198173,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,05/25/2018,21:00:00,REGULAR,2898829,386702

In [18]:
df_may18_week2.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/05/2018,00:00:00,REGULAR,6607801,2239047
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/05/2018,04:00:00,REGULAR,6607821,2239051
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/05/2018,08:00:00,REGULAR,6607830,2239083
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/05/2018,12:00:00,REGULAR,6607921,2239160
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,6608151,2239219